version: '3'
services:
    db-user:
        container_name: mysql_db_user
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: 'warung_alfin_user'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '3307:3306'
        expose: 
            - '3307'
        volumes:
            - ./docker/sql/user/:/docker-entrypoint-initdb.d
            - ./docker/development/db/user/:/var/lib/mysql
    db-product:
        container_name: mysql_db_product
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: 'warung_alfin_product'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '3308:3306'
        expose: 
            - '3308'
        volumes:
            - ./docker/sql/product/:/docker-entrypoint-initdb.d
            - ./docker/development/db/product/:/var/lib/mysql
    db-cart:
        container_name: mysql_db_cart
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: 'warung_alfin_cart'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '3309:3306'
        expose: 
            - '3309'
        volumes:
            - ./docker/sql/cart/:/docker-entrypoint-initdb.d
            - ./docker/development/db/cart/:/var/lib/mysql
    db-order:
        container_name: mysql_db_order
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: 'warung_alfin_order'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '3310:3306'
        expose: 
            - '3310'
        volumes:
            - ./docker/sql/order/:/docker-entrypoint-initdb.d
            - ./docker/development/db/order/:/var/lib/mysql
    db-payment:
        container_name: mysql_db_payment
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: 'warung_alfin_payment'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - '3311:3306'
        expose: 
            - '3311'
        volumes:
            - ./docker/sql/payment/:/docker-entrypoint-initdb.d
            - ./docker/development/db/payment/:/var/lib/mysql
    gqlserver:
        build: ./gqlserver
    grpc-user:
        build: ./service/user